---
- name: "[Miroir] Check already installed"
  stat:
    path: /opt/miroir/{{ version.miroir }}
  register: miroir_installed

- when: not miroir_installed.stat.exists
  become: yes
  block:
    - name: "[Miroir] Clone"
      git:
        repo: https://github.com/tadashi-aikawa/miroir.git
        dest: /opt/miroir/{{ version.miroir }}
        version: "{{ version.miroir }}"
        depth: 1

    - name: "[Miroir] Build and deploy"
      make:
        chdir: /opt/miroir/{{ version.miroir }}
        target: "{{ item }}"
      items:
        - init
        - package
        - deploy-container
