---
- name: "Check pyenv already installed"
  stat:
    path: ~/.pyenv
  register: pyenv_installed

- when: not pyenv_installed.stat.exists
  block:
    - become: yes
      apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev
    - git:
        repo: "https://github.com/pyenv/pyenv.git"
        dest: ~/.pyenv
        depth: 1
    - blockinfile:
        path: ~/.bash_profile
        create: yes
        block: |
          export PYENV_ROOT="${HOME}/.pyenv"
          if [ -d "${PYENV_ROOT}" ]; then
              export PATH=${PYENV_ROOT}/bin:$PATH
              eval "$(pyenv init -)"
          fi
