title: Simple

one:
  name: One endpoint
  host: http://localhost/api/simple/one

other:
  name: Other endpoint
  host: http://localhost/api/simple/other


addons:
  log2reqs:
    name: plain
    config:
      encoding: utf8
