---
- name: "[LocalStack] Running as container"
  become: yes
  docker_container:
    name: localstack
    image: localstack/localstack:{{ version.localstack }}
    ports:
      - 4567:4567
      - 4568:4568
      - 4569:4569
      - 4570:4570
      - 4571:4571
      - 4572:4572
      - 4573:4573
      - 4574:4574
      - 4575:4575
      - 4576:4576
      - 4577:4577
      - 4578:4578
      - 4579:4579
      - 4580:4580
      - 4581:4581
    restart: yes
    restart_policy: always

- name: "[LocalStack] Create bootstrap script"
  template:
    src: bootstrap.sh
    dest: ~/
    mode: "u=rwx,g=rx,o=rx"
