title: Ignore properties

one:
  name: One endpoint
  host: http://localhost/api/ignore_properties/one

other:
  name: Other endpoint
  host: http://localhost/api/ignore_properties/other


output:
  encoding: utf8
  response_dir: response
  logger:  # (See http://wingware.com/psupport/python-manual/3.4/library/logging.config.html#logging-config-dictschema)
    version: 1
    formatters:
      simple:
        format: '%(levelname)s %(message)s'
    handlers:
      console:
        class : logging.StreamHandler
        formatter: simple
        level   : INFO
        stream  : ext://sys.stderr
    root:
      level: INFO
      handlers: [console]

addons:
  log2reqs:
    name: jumeaux.addons.log2reqs.csv
    config:
      encoding: utf8

  res2dict:
    - name: jumeaux.addons.res2dict.json

  judgement:
    - name: jumeaux.addons.judgement.ignore_properties
      config:
        ignores:
          - title: Ignore ignored_id
            conditions:
              - changed:
                  - root<'ignored_id'>
          - title: Ignore favorite only if path includes `/same`
            conditions:
              - path: .*/same.*
                added: [root<'members'><\d+><'favorite'>.*]
                changed: [root<'members'><\d+><'favorite'>.*]
                removed: [root<'members'><\d+><'favorite'>.*]

  store_criterion:
    - name: jumeaux.addons.store_criterion.general
      config:
        statuses:
          - different

  did_challenge:
    - name: jumeaux.addons.did_challenge.sleep
      config:
        min: 0.5
        max: 0.5

  dump:
    - name: jumeaux.addons.dump.json
    - name: jumeaux.addons.dump.xml

  final:
    - name: jumeaux.addons.final.aws
      config:
        table: jumeaux-viewer
        bucket: mamansoft-jumeaux-viewer
        cache_max_age: 120
        checklist: sample
        local_stack:
          use: true


