title: Ignore properties

one:
  name: One endpoint
  host: http://localhost/api/ignore_properties/one

other:
  name: Other endpoint
  host: http://localhost/api/ignore_properties/other


addons:
  log2reqs:
    name: jumeaux.addons.log2reqs.csv
    config:
      encoding: utf8

  judgement:
    - name: jumeaux.addons.judgement.ignore_properties
      config:
        ignores:
          - title: Ignore ignored_id
            conditions:
              - changed:
                  - root<'ignored_id'>
          - title: Ignore favorite only if path includes `/same`
            conditions:
              - path: .*/same.*
                added: [root<'members'><\d+><'favorite'>.*]
                changed: [root<'members'><\d+><'favorite'>.*]
                removed: [root<'members'><\d+><'favorite'>.*]
