- hosts: all
  connection: local
  tasks:
    - name: Check python installed
      stat:
        path: "~/.pyenv/versions/{{ version.python3 }}"
      register: python_is_installed

    - name: Install python
      shell: '. ~/.bash_profile && pyenv install {{ version.python3 }}'
      when: not python_is_installed.stat.exists

    - name: Install Jumeaux {{version.jumeaux}} from pip
      shell: '. ~/.bash_profile && pyenv global {{ version.python3 }} && pip install jumeaux=={{ version.jumeaux }}'

    - name: Create .aws directory
      file:
        path: ~/.aws
        state: directory

    - name: Configure .aws/config
      blockinfile:
        path: ~/.aws/config
        create: yes
        block: |
          [default]
          region = ap-northeast-1

    - name: Configure .aws/credentials (dummy)
      blockinfile:
        path: ~/.aws/credentials
        create: yes
        block: |
          [default]
          aws_access_key_id = hoge
          aws_secret_access_key = hoge
