- hosts: all
  connection: local
  tasks:
    - name: Install dependencies
      become: yes
      apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - make
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev

    - name: Check pyenv installed
      stat:
        path: ~/.pyenv
      register: pyenv_is_installed

    - name: Install pyenv
      shell: git clone --depth 1 https://github.com/pyenv/pyenv.git ~/.pyenv
      when: not pyenv_is_installed.stat.exists

    - name: Configure bash_profile
      blockinfile:
        path: ~/.bash_profile
        create: yes
        block: |
          export PYENV_ROOT="${HOME}/.pyenv"
          if [ -d "${PYENV_ROOT}" ]; then
              export PATH=${PYENV_ROOT}/bin:$PATH
              eval "$(pyenv init -)"
          fi

