- hosts: all
  connection: local
  become: yes
  vars:
    document_root: /var/www/html
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      notify: Restart nginx

    - name: Disable Sendfile
      lineinfile: 
        dest: '/etc/nginx/nginx.conf'
        regexp: '^\s*sendfile'
        line: 'sendfile off;'
        state: present
      notify:
        - Restart nginx

    - name: Create symlinks to nginx document root
      file:
        src: '/jumeaux'
        dest: '{{ document_root }}/api'
        force: yes
        state: link

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
