output:
  encoding: utf8
  response_dir: response
  logger:  # (See http://wingware.com/psupport/python-manual/3.4/library/logging.config.html#logging-config-dictschema)
    version: 1
    formatters:
      simple:
        format: '%(levelname)s %(message)s'
    handlers:
      console:
        class : logging.StreamHandler
        formatter: simple
        level   : INFO
        stream  : ext://sys.stderr
    root:
      level: INFO
      handlers: [console]

addons:
  res2dict:
    - name: json
    - name: xml

  store_criterion:
    - name: general
      config:
        statuses:
          - different

  did_challenge:
    - name: sleep
      config:
        min: 0.5
        max: 0.5

  dump:
    - name: json
    - name: xml

  final:
    - name: miroir
      config:
        table: miroir
        bucket: mamansoft-miroir
        cache_max_age: 120
        checklist: sample
        local_stack:
          use: true


