title: Ignore order

one:
  name: One endpoint
  host: http://localhost/api/ignore_order/one

other:
  name: Other endpoint
  host: http://localhost/api/ignore_order/other


addons:
  log2reqs:
    name: csv
    config:
      encoding: utf8

  res2res:
    - name: json_sort
      config:
        items:
          - conditions:
              - path:
                  items:
                    - regexp: /M-.+
            targets:
              - path: root<'list1'><0><'favorite'>
